# This workflow deploys th PilotsAltimeter.app github pages side from the private repo: TwoMorrowsTech/PilotsAltimeter.app.
name: Deploy

# Can run manually or be triggered by another workflow
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'The src repo to deploy the site from.'
        default: 'pilotsaltimeter.app'
        type: choice
        options:
          - pilotsaltimeter.app
      artifact-name:
        description: "The name of the artifact uploaded in the src repo's workflow."
        default: 'github-pages'
        type: choice
        options:
          - github-pages
          - github-pages-encrypted
      run-id:
        description: 'The run id of the workflow that uploaded the artifact in the src repo.'
        required: true

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_PAGES_DEPLOY_APP_APP_ID }}
          private-key: ${{ secrets.GH_PAGES_DEPLOY_APP_PRIVATE_KEY }}
          repositories: ${{ inputs.repo }}
      - uses: twomorrowstech/deploy-gh-pages-from-private-repo-action@v1
        with:
          repo: ${{ inputs.repo }}
          run-id: ${{ inputs.run-id }}
          artifact-name: ${{ inputs.artifact-name }}
          github-token: ${{ steps.app-token.outputs.token }}